### PR TITLE
Closes #75. Properly set the conditions when call to applyOutputs fails.

### LINKED ISSUE #75: Ready status is true when outputs fail to apply
## tl;dr:

Whenever the `fsmReconciler` fails to `applyOutputs()`, the object's `Ready` status is always unexpectedly `True` 🙀 

## Details

The "Ready" condition's status is always set to:

- `True` if all other conditions are `True`; or,
- `False` if any other condition is `False`

However, when the `fsmReconciler` fails to `applyOutputs()`, no `False` condition is ever set within the returned `conditions`!

https://github.com/reddit/achilles-sdk/blob/23adbe7cc9cbab1cc34643f4b313cfa0b915faca/pkg/fsm/internal/reconciler.go#L288-L295

As a result, the resource's `Ready` status will always show as `True` despite this failure.

## Proposed Fix

All other code paths through [the main loop](https://github.com/reddit/achilles-sdk/blob/23adbe7cc9cbab1cc34643f4b313cfa0b915faca/pkg/fsm/internal/reconciler.go#L235) seem to apply the current `condition` to `conditions` before returning:

- When the result is not done:

  https://github.com/reddit/achilles-sdk/blob/23adbe7cc9cbab1cc34643f4b313cfa0b915faca/pkg/fsm/internal/reconciler.go#L272-L280

- When the result is done, and the outputs are applied successfully:

  https://github.com/reddit/achilles-sdk/blob/23adbe7cc9cbab1cc34643f4b313cfa0b915faca/pkg/fsm/internal/reconciler.go#L292-L295

So perhaps failures applying outputs should take any non-empty `condition` and:

- Falsify the status
- Set the reason and message to something indicating the failure to apply resources
- Set that onto `conditions` before returning

That would align the condition handling with the other code paths and ensure that output failures don't cause the resource to report an "incorrect" status of being ready.

### PR DESCRIPTION
**Pull request by karanthukral**
Closes https://github.com/reddit/achilles-sdk/issues/75

Managing the PR process for @dansawyer73 

## 💸 TL;DR
- Ensure the status condition is updated to be false when `ApplyOutputs` fails. This ensures that the resource is not marked ready when status conditions fail

## 🧪 Testing Steps / Validation
- Couldn't figure out a sane way to test this in envtests without needing to use a fake client. Ended up using manual verification in a couple of internal controllers.
- Updated the sdk version in a controller locally and ran all tests to ensure the behaviour remains consistent for current users
- Updated controller to try to create a deployment in a namespace that doesn't exist and the status of the object is shown below:

```
- lastTransitionTime: "2025-12-04T19:56:45Z"
      message: 'Failed to apply outputs: ensuring outputs: ensuring /, Kind= broken-deployment:
        cannot create object: namespaces "namespace-does-not-exist" not found'
      observedGeneration: 7
      reason: ApplyOutputsFailed
      status: "False"
      type: ContainerPrefixFetched
    - lastTransitionTime: "2025-12-04T19:56:45Z"
      message: 'Non-successful conditions: ContainerPrefixFetched'
      observedGeneration: 7
      reason: ConditionsFailed
      status: "False"
      type: Ready
```

If anyone has ideas on how best to test this in env/unit tests let me know

## ✅ Checks

- [ ] CI tests (if present) are passing
- [ ] Adheres to code style for repo
- [ ] Contributor License Agreement (CLA) completed if not a Reddit employee

### CODE REVIEW

**Comment by karanthukral** [comment]
Created a draft PR that I will get tested tomorrow hopefully and opened for actual review

File: pkg/fsm/internal/reconciler.go [hunk 1]
```diff
@@ -287,6 +287,13 @@ func (r *fsmReconciler[T, Obj]) reconcile(
 		}
 
 		if err := r.applyOutputs(ctx, log, obj, out); err != nil {
+			// Mark the state's condition as failed since outputs couldn't be applied
+			if !condition.IsEmpty() {
```
Comment (kdorosh) [inline pkg/fsm/internal/reconciler.go:291]: should we do this even if the condition isn't empty?

**Review by kdorosh — COMMENTED** [review]
one question for my own understanding

File: pkg/fsm/internal/reconciler.go (hunk 1 above)
Comment (karanthukral) [reply pkg/fsm/internal/reconciler.go:291]: good question, let me think about it. The only weird part of that would be what is the condition type since we are overriding other fields here? Should it just be empty? 🤔 

The `IsEmpty` returns true only if all fields are empty - https://github.com/reddit/achilles-sdk-api/blob/main/api/condition.go#L115

Comment (karanthukral) [reply pkg/fsm/internal/reconciler.go:291]: We also seem to do this same check when setting any other fields for the condition too - https://github.com/reddit/achilles-sdk/blob/04c816eae87fdc4eae57be33cd0c18f943688c54/pkg/fsm/internal/reconciler.go#L276

**Review by jessicayuen — APPROVED** [review]

File: pkg/fsm/internal/reconciler.go (hunk 1 above)
Comment (kdorosh) [reply pkg/fsm/internal/reconciler.go:291]: yeah, I think the change as you have it is safer / less intrusive

**Review by kdorosh — APPROVED** [review]
